env:
  DOCKER_COMPOSE_VERSION: 1.14.0
  GRADLE_VERSION: 4.0.1
language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
script:
- gradle -v
- cd /usr/local
- curl -LO https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip
- ln -s gradle-${GRADLE_VERSION} gradle && export PATH=/usr/local/gradle/bin:$PATH
- cd caom2-meta-ui
- gradle clean dockerize
- cd ../caom2-search-server
- gradle clean install
- cd examples/default
- gradle clean dockerize
- cd ../_int_test_
- docker-compose up -d
- docker ps -a
- cd ../default
- gradle -i -PintTest_selenium_server_url=http://localhost:4444 -PintTest_web_app_url=http://proxy.cadc.dao.nrc.ca
  -PintTest_web_app_endpoint=/search/ intTestFirefox
after_success:
- if [ "$(. ./can-deploy.sh)" = "DEPLOY" ]; then docker login -u="$DOCKER_USERNAME"
  -p="$DOCKER_PASSWORD"; docker push opencadc/archive-search; fi
- if [ "$(. ./can-deploy.sh)" != "DEPLOY" ]; then echo "Not deploying."; fi
notifications:
  slack:
    secure: cZECco78mN3ZdEmLRSjH26KShRQV0awRRFp77HzFCttlcNPCPDn0o4vI0nW7Jqi5qBvPTYmaYLjcJah9+nvaJQnKnYZTNy0b4q9dch8h5456kiN4Tsi98yxxp5IMGgXoxHEBGiYvBnnqiL3RmoCH6Z2FifekO/36HyyMFSn5cwF/2lvyJp7lxq+sRQHcp4BjcPrR19nd54AIvoEtxfnjsIo6WIuQkBXuUaHOD+0qpR8nbT2cR5bP/h+Fq9tJH+/2HuLiGNzOH6rkMBCyqD57OTTffvgsfiw+TUcqhCKwDa3MbZG4SZfM8m6J8tjusC1YtuxHkSS+dcgxBLWwFx//y9gFHGuFExzW5AZTYlWf91kSD6TqtElN8FFvhIYGJ3j1XKDL3TgYbliTU/3cCVIeiCbZA/Hh/t5o6L/XZmQOiMbSCJGGHiyyg/nmltdLaxzOnHZr0sR4UeywQCMXQrK3U3X1qA3DeXTOzi6WoDHlKkqek8MsThLsCgGw39+tfVPYW0Jns+rnMtLeZSQ8maeJGrGAxi8b8UXHULIiuPljOZIYhyC4K32pqe60R0LnMuwURXGv3eozcrq9bixKd7IbqPSQc3+mrcTeVMuDiJ/P57KcbWRozES99Y7vhXkfVZ9cTjZXo4aexkvLEdVYUBulwOXXINRTKICzM1EPS9i3+Lk=
