version: '2'
services:
  ui:
    image: mach378.cadc.dao.nrc.ca:5000/opencadc_search
    ports:
      - '8080:8080'
      - '5555:5555'
    networks:
      - 'caom2'
    depends_on:
      - tap
      - caom2ui
    volumes:
      - /usr/local/search/webapps:/usr/local/tomcat/webapps
  caom2ui:
    image: opencadc/caom2ui
    ports:
      - '3080:8080'
      - '3555:5555'
    networks:
      - 'caom2'
    volumes:
      - /usr/local/caom2ui/webapps:/usr/local/tomcat/webapps
  tap:
    image: opencadc/tap
    ports:
      - '8880:8080'
      - '8855:5555'
    networks:
      - 'caom2'
    depends_on:
      - tappg
    volumes:
      - /usr/local/tap/webapps:/usr/local/tomcat/webapps
  tappg:
    image: opencadc/tap_postgres
    networks:
      - 'caom2'
    environment:
      - POSTGRES_USER=tap
      - POSTGRES_PASSWORD=astr0query
      - PGDATA=/var/lib/postgresql/data/tap
    volumes:
      - /var/lib/postgresql/data
      - /var/run/postgresql

# Create the network 'archive' for which this system will run within.
networks:
  caom2:
    driver: 'bridge'
