version: '2'
services:
  ui:
    image: opencadc/search
    ports:
      - '8080:8080'
      - '5555:5555'
    networks:
      - 'caom2'
    environment:
      - 'CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5555 -Djava.security.egd=file:/dev/./urandom -Djsse.enableSNIExtension=false -Dorg.opencadc.search.theme=base -Dcadc.search.obs-core=true -Dorg.opencadc.search.max-row-count=30000 -Dorg.opencadc.search.tap-service-id=ivo://cadc.nrc.ca/tap -Dorg.opencadc.search.caom2ui-host=caom2ui:8080 -Dca.nrc.cadc.reg.client.RegistryClient.host=tap:8080'
    depends_on:
      - tap
      - caom2ui
    volumes:
      - /usr/local/search/webapps:/usr/local/tomcat/webapps
  caom2ui:
    image: opencadc/caom2ui
    networks:
      - 'caom2'
  tap:
    image: opencadc/tap
    ports:
      - '9080:8080'
    networks:
      - 'caom2'
    depends_on:
      - tappg
    volumes:
      - /usr/local/tap/webapps:/usr/local/tomcat/webapps
  tappg:
    image: opencadc/tap_postgres
    networks:
      - 'caom2'
    environment:
      - POSTGRES_USER=tap
      - POSTGRES_PASSWORD=astr0query
      - PGDATA=/var/lib/postgresql/data/tap
    volumes:
      - /var/lib/postgresql/data
      - /var/run/postgresql

# Create the network 'archive' for which this system will run within.
networks:
  caom2:
    driver: 'bridge'
