version: '2'
services:
  ui:
    image: opencadc/search
    ports:
      - '8080:8080'
      - '5555:5555'
    networks:
      - 'caom2'
    depends_on:
      - tap
      - caom2ui
      - uwspg
    volumes:
      - /usr/local/tomcat/webapps
  uwspg:
    image: opencadc/uws_postgres
    networks:
      - 'caom2'
    environment:
      - POSTGRES_USER=uws
      - POSTGRES_PASSWORD=astr0query
      - PGDATA=/var/lib/postgresql/data/uws
    volumes:
      - /var/lib/postgresql/data
      - /var/run/postgresql
  caom2ops:
    image: opencadc/caom2ops
    ports:
#      - '6080:8080'
      - '6555:5555'
    networks:
      - 'caom2'
    depends_on:
      - caom2opspg
    volumes:
      - /usr/local/tomcat/webapps
      - /root/.pub
  caom2opspg:
    image: opencadc/uws_postgres
    networks:
      - 'caom2'
    environment:
      - POSTGRES_USER=caom2ops
      - POSTGRES_PASSWORD=astr0query
      - PGDATA=/var/lib/postgresql/data/uws
    volumes:
      - /var/lib/postgresql/data
      - /var/run/postgresql
  caom2ui:
    image: opencadc/caom2ui
#    ports:
#      - '3080:8080'
#      - '3555:5555'
    networks:
      - 'caom2'
    volumes:
      - /usr/local/tomcat/webapps
    depends_on:
      - caom2ops
  tap:
    image: opencadc/tap
    ports:
#      - '4080:8080'
      - '4555:5555'
    networks:
      - 'caom2'
    depends_on:
      - tappg
    volumes:
      - /usr/local/tomcat/webapps
      - /root/.pub
  tappg:
    image: opencadc/tap_postgres
    networks:
      - 'caom2'
    environment:
      - POSTGRES_USER=tap
      - POSTGRES_PASSWORD=astr0query
      - PGDATA=/var/lib/postgresql/data/tap
    volumes:
      - /var/lib/postgresql/data
      - /var/run/postgresql

# Create the network 'archive' for which this system will run within.
networks:
  caom2:
    driver: 'bridge'
